version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-restaurants"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cv7fii2d8xg3"
s3_prefix = "sam-app-restaurants"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
