version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "restaurants-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aa6tw802hl21"
s3_prefix = "restaurants-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
